### ISSUE TITLE
Manual Setup Code for OneLogin Authenticator

### ISSUE THREAD

**Issue by szhuphx** [BrandonPotter/GoogleAuthenticator#141]
Hi - 
First of all I want to thank you for sharing this library! 

I implemented an MFA project using this library, and found one issue with OneLogin app. I investigated a bit, but has no luck on it. So just want to ask it here - 

I tested this library, and it can be successfully used by Google Authenticator, Microsoft Authenticator, Duo Security with both QR code and Manual Setup code. With OneLogin App, however, the Manual Setup Code generated in this library is not valid, although the QR code works. I don't know what is the encode algorithm for OneLogin app, it looks it will only take 9 or 10 digit-only code.

If any one could help, that will be greatly appreciated!!

Thanks

**Comment by ahwm** [comment]
From what I have been able to determine, OneLogin is not intended for use by the general public in a way that makes sense to try and incorporate into the library. It seems to be a proprietary system designed to protect corporate assets using a single sign in to OneLogin itself.

As such, it looks like you should use their API to generate/verify tokens rather than this library: https://developers.onelogin.com/api-docs/2/multi-factor-authentication/enroll-factor
