### ISSUE TITLE
Update to use .Net 6

### ISSUE THREAD

**Issue by ragavendra** [BrandonPotter/GoogleAuthenticator#154]
Can we have the samples updated to use .Net 6.0 and/ or higher.

Also, nice to have either requirements to setup the Authenticator app in Readme file or in the code comments.

**Comment by ragavendra** [comment]
hi,

When I try to build the web sample, I get the below error.

`/home/user/.dotnet/sdk/6.0.xx/Microsoft.Common.CurrentVersion.targets(1217,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.6.2 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/user/authrepo/GoogleAuthenticator/Google.Authenticator.WebSample/Google.Authenticator.WebSample.csproj]

Build FAILED.
`
I am assuming because I have .Net 6.0 in my machine.

In the README it says to store the key, which key is it referring to? Is it the app key we get from creating the app in the Google developer site.

**Comment by ahwm** [comment]
Ah, I see. Okay, yeah. The samples only work on Windows. I will work on porting those.

The "key" that's referenced is the secret key that your application generates for the specific user. So a user will make some request to enable 2FA/Google Authenticator through your application and a secure key is generated. That key is what is stored in your application because you have to use the same key (or "secret") every time you authenticate a user's TOTP.

**Comment by ahwm** [comment]
@ragavendra Here's the web sample in .NET 6: https://github.com/BrandonPotter/GoogleAuthenticator/tree/sample-ports/GoogleAuthenticator.WebCoreSample

**Comment by ragavendra** [comment]
@ahwm .... thanks a lot for this. This is working in .Net6.0 now. I was actually writing similar snippet and thought to send a pull request for the same.

Please let me know if there is similar areas for contribution as this can help me improve my C# skills.
