### ISSUE TITLE
Code valid after 15seconds

### ISSUE THREAD

**Issue by ebinroy** [BrandonPotter/GoogleAuthenticator#160]
Hi All, I am having issue with the code that will return valid after 15seconds only. I mean the code shows on authenticator app will be valid after 15 second. I noticed that the mobile time is 15second ahead than the server time. A detailed issue is posted at stack overflow. Kindly check on this. I am not sure whether its my lack of knowledge to deal with this. Thanks

https://stackoverflow.com/questions/76361311/two-factor-authentication-code-validation-expiry-issues-in-google-microsoft-auth

**Comment by ahwm** [comment]
If I'm understanding the issue correctly, this is expected behavior. The time tolerance is intended to allow the code to be valid for x periods before and after to adjust for time sync issues. You will see this same behavior on sites like Google or Amazon Web Services where you can enter a code and wait several seconds after the code changes in your app and still have it be valid. They can just be using different tolerances.

@flytzen anything you see that I may be missing here?

**Comment by flytzen** [comment]
You should normally not use `GetCurrentPin` yourself, unless you are writing an authenticator app (this library is not intended for that, in any case).

`GetCurrentPin` will give you the *current* PIN for the time on the device where the code runs. This is exactly what an authenticator app does. There is no way to get `GetCurrentPin` to return a code for some other time window - that would be against the whole design of TOTP.

When a user sends a code to your app, you should use `ValidateTwoFactorPIN` (or, at a pinch, `GetCurrentPINs` which return an array of codes) to validate the code. The Validate method will generate all the valid codes for the time window and will check if the single user-provided code matches any one of them. 

Hope that makes sense.

**Comment by flytzen** [comment]
Hmmm. The scenario you have described should work - you can try adding a unit test that checks it.

But let's just look at what is supposed to happen and maybe we can work it out together.

- TOTP works by dividing time since 1 January 1970 into 30 second *intervals*. 
- Each *interval* will generate a unique 6-digit code when combined with the shared secret.
- On the authenticator app, every time the clock ticks over at 30 and 0 seconds, a new code is displayed to the user.
- When you call the Validate function, it will take the timespan and divide it by 30 to work out how many intervals either side of the current one on the server it should use. [**However, it only does that if the specified interval is more than 30 seconds**.](https://github.com/BrandonPotter/GoogleAuthenticator/blob/7187f1f8efb26eca9f749aeeb168c7a05f7a1a12/Google.Authenticator/TwoFactorAuthenticator.cs#L306). If you pass in exactly 30 seconds, it will be treated as 0 and the code will not be compared to any other intervals. *This looks like a bug to me*. 

Workaround: Specify a time interval longer than 30 seconds - even 31 seconds should work. I would *strongly* recommend that you specify an interval closer to five minutes - clock drift is common and having an interval down at less than a minute is just going to hurt. 

I think we should fix this, but as the workaround is easy, releasing a new version won't be a high priority - @ahwm ? (I am happy to do the code fix and we can just roll it in to the next release).

@ebinroy - I suspect this would work when you specify 45 seconds ? Although, please remember that everything you specify effectively get rounded *down* to the nearest 30 seconds so 59 == 30 in this case.

**Comment by ahwm** [comment]
Ohh okay. That's making more sense. I looked at it too early in the day and clearly didn't read thoroughly enough. Hah!

I think rolling into next release is fine. I don't expect a lot of people are using such a short window. After all, if they don't specify a value themselves it's using the default of 5 minutes. If it's a big enough issue for @ebinroy then we could just do a 3.1.1 release.

**Comment by ahwm** [comment]
@ebinroy can you try with 3.1.1-beta1 and see if you encounter similar issues? https://www.nuget.org/packages/GoogleAuthenticator/3.1.1-beta1

**Comment by ebinroy** [comment]
Thanks for the newer version.

What I feel is it will be good if you have a method like below and will adjust the time difference (between user server time & actual UTC time) and do the the verification. it will be helpful for the users who want to do the validation for a shorter period( means the code wont be valid after Authentication app disappears the code +-5sec)

`public bool ValidateTwoFactorPIN(string accountSecretKey, string twoFactorCodeFromClient, DateTime currentDatetimeUTC)`

**Comment by flytzen** [comment]
Hi @ebinroy. Thank you for the suggestion. I can say for sure that we will not do that as it will open a security hole and violate the underlying concept of TOTP :)

The point of TOTP is that you have a code that changes every 30 seconds. This prevents a replay attack: If an attacker intercepts your code it is useless five minutes later.
If you allow the client to specify what time to use, then an attacker will be able to use an old code by specifying the time the original code was generated. So, you would then want to limit how much the passed-in time is allowed to differ from the server time. At that point, you are back to the current functionality, which allows you to specify the time window to allow for clock drift.
