### ISSUE TITLE
Allow varying window sizes

### ISSUE THREAD

**Issue by asmith3006** [BrandonPotter/GoogleAuthenticator#206]
Currently this library is (I believe) hard coded to 30 second intervals. The TOTP standard allows for other intervals, 

Would you consider adding options for 60 seconds?

**Comment by ahwm** [comment]
As a large majority of apps only support 30 second intervals (Google Authenticator included), it feels out of scope, though certainly open for discussion.

I would recommend using the drift tolerance to accommodate this rather than adjusting the interval length (the RFC refers to this as "time-step size"). The default drift tolerance is 5 minutes so even though a token is "valid" for 30 seconds, the user has an additional 4 minutes 30 seconds to enter it.

You can specify your own drift tolerance using an overload of `ValidateTwoFactorPIN` like so:

```c#

var tfa = new TwoFactorAuthenticator();

var isValid = tfa.ValidateTwoFactorPIN(key, code, 5); // specify in time-step counts
var isValid = tfa.ValidateTwoFactorPIN(key, code, 5, isSecretBase32); // specify in time-step counts

var isValid = tfa.ValidateTwoFactorPIN(key, code, TimeSpan.FromMinutes(2.5)); // specify in time
var isValid = tfa.ValidateTwoFactorPIN(key, code, TimeSpan.FromMinutes(2.5), isSecretBase32); // specify in time

```

@flytzen @BrandonPotter thoughts on allowing different time-step sizes? I know some apps, such as 2FAS, support 10-second intervals.

**Comment by flytzen** [comment]
@asmith3006 @ahwm 
I think the question is - what is the real-world use-case? I appreciate that the spec *allows* it - but is that actually used in practice? For usecases where this library is relevant?

It's probably not very hard to implement - but it is more to maintain and another potential source of bugs so it would really require a solid usecase.

**Comment by asmith3006** [comment]
We are implementing MFA for our internal systems and have a group of people who are not permitted to carry phones during the day. We are investigating different physical tokens and have found some which are credit card sized and would work well in our environment. 

Unfortunately these cards are hard coded to 60 second increments so we need to change the validation. So our use case is when validating codes against physical tokens rather than apps. 

(We can't use the drift tolerance, if the number of 30 second intervals is 57010869 then the number of 60 second intervals is 28505434 so we'd need a drift interval of 28,505,435 - unless I've misunderstood how the drift interval works. )

**Comment by flytzen** [comment]
Yes, that makes sense, thank you.
That value is not used in many places so I don't think it would be too much work to change it.
I *would* worry about changing the API by adding yet another overload to various methods, though: It is confusing enough as it is :D 
If we were to do this, I think it should be a *constructor* param. I think that would be pretty easy; main job is actually to tidy up - I think - one private method that allows an overload for this and get rid of that.
Thoughts @ahwm ?

I don't mind doing it, I could do with a fun distraction :) But it *is* code to maintain and test for.

**Comment by ahwm** [comment]
I'd say go for it. I agree with it being in the constructor rather than another overload.
